export type StudentResourceCategory =
  | "Daily Tools"
  | "Canvas & IT"
  | "Academic Planning"
  | "Exams"
  | "Library & Research"
  | "Careers"
  | "Financial Aid"
  | "Campus & Facilities"
  | "Policies & Forms"
  | "Wellbeing & Support"
  | "Contacts";

export type StudentResource = {
  id: string;
  label: string;
  href: string;
  category: StudentResourceCategory;
  description: string;
  keywords: readonly string[];
  showOnHome?: boolean;
  audience?: readonly string[];
};

export const studentResources = [
  {
    id: "suss-portal",
    label: "SUSS Portal",
    href: "https://portal.suss.edu.sg",
    category: "Daily Tools",
    description: "Student portal for enrolment, admin services, records, and student transactions.",
    keywords: ["student portal", "portal", "sims", "backpack", "admin", "eservices", "enrolment", "enrollment", "fees", "records", "results", "grades", "transcript", "profile"],
    showOnHome: true,
  },
  {
    id: "canvas",
    label: "Canvas",
    href: "https://canvas.suss.edu.sg",
    category: "Daily Tools",
    description: "Canvas LMS for course sites, announcements, assignments, and class materials.",
    keywords: ["canvas lms", "lms", "learning management system", "classes", "assignments", "modules", "course site", "announcements", "quizzes", "calendar", "inbox", "deadlines", "submissions", "lesson"],
    showOnHome: true,
  },
  {
    id: "mymail",
    label: "MyMail",
    href: "https://outlook.office365.com",
    category: "Daily Tools",
    description: "SUSS student email through Outlook and Office 365.",
    keywords: ["email", "outlook", "office 365", "microsoft 365", "mail", "mymail", "student email", "inbox", "webmail"],
    showOnHome: true,
  },
  {
    id: "library",
    label: "SUSS Library",
    href: "https://library.suss.edu.sg",
    category: "Library & Research",
    description: "Library homepage for research help, facilities, services, and library updates.",
    keywords: ["library", "research", "books", "articles", "journal", "journals", "database", "databases", "study space", "opening hours", "resources"],
  },
  {
    id: "career-portal",
    label: "Career Portal",
    href: "https://susscareerportal.suss.edu.sg",
    category: "Careers",
    description: "Career portal for opportunities, career tools, and Kinobi services.",
    keywords: ["career", "kinobi", "jobs", "resume", "cv", "internship", "employment", "job portal", "career portal", "cover letter", "interview"],
  },
  {
    id: "istudyguide",
    label: "iStudyGuide",
    href: "https://isg.suss.edu.sg",
    category: "Daily Tools",
    description: "iStudyGuide and course study guidance resources.",
    keywords: ["isg", "i smart guide", "ismart guide", "study guide", "istudyguide", "course guide", "study plan", "learning guide"],
    showOnHome: true,
  },
  {
    id: "adles",
    label: "ADLeS",
    href: "https://adles.suss.edu.sg",
    category: "Canvas & IT",
    description: "ADLeS platform for SUSS learning services.",
    keywords: ["adles", "learning", "platform", "e-learning", "online learning", "courseware"],
  },
  {
    id: "exam-timetable",
    label: "Exam Timetable",
    href: "https://www.suss.edu.sg/docs/default-source/dept_as/ca/exam-timetable.pdf",
    category: "Exams",
    description: "Latest examination timetable published by SUSS.",
    keywords: ["exam timetable", "exams", "assessment", "pdf", "exam schedule", "exam dates", "final exam", "oes", "eca"],
    showOnHome: true,
  },
  {
    id: "minors-overview",
    label: "Minors Overview",
    href: "https://www.suss.edu.sg/academics/programmes/part-time-undergraduate/minor",
    category: "Academic Planning",
    description: "Overview of SUSS minors for undergraduate students.",
    keywords: ["minor", "minors", "undergraduate", "programme", "program", "specialisation", "specialization", "electives"],
  },
  {
    id: "new-suss-curriculum",
    label: "New SUSS Curriculum",
    href: "https://www.suss.edu.sg/academics/why-suss/new-suss-curriculum",
    category: "Academic Planning",
    description: "Information about the new SUSS curriculum structure.",
    keywords: ["new curriculum", "curriculum", "common curriculum", "degree", "graduation requirements", "programme structure", "program structure", "core courses"],
  },
  {
    id: "credit-waivers",
    label: "Credit Waivers and Recognitions",
    href: "https://www.suss.edu.sg/life-at-suss/onboarding/matriculation/credit-waivers-credit-recognitions",
    category: "Academic Planning",
    description: "Credit waiver and credit recognition information for prior learning or completed studies.",
    keywords: ["credit waiver", "credit recognition", "exemption", "transfer credit", "cr", "recognition", "prior learning", "course exemption"],
  },
  {
    id: "library-search",
    label: "Library Search",
    href: "https://search.library.suss.edu.sg/primo-explore/search?vid=SUSS&lang=en_US",
    category: "Library & Research",
    description: "Search the SUSS Library catalogue and discovery system.",
    keywords: ["library search", "catalogue", "catalog", "primo", "discovery", "books", "articles", "journal", "journals", "ebook", "e-book"],
  },
  {
    id: "databases-az",
    label: "Databases A-Z",
    href: "https://libguides.suss.edu.sg/az/databases",
    category: "Library & Research",
    description: "A-Z list of SUSS Library databases.",
    keywords: ["databases", "database", "a-z", "az", "research", "journals", "articles", "academic sources", "library databases"],
  },
  {
    id: "research-guides",
    label: "Research Guides",
    href: "https://libguides.suss.edu.sg/researchguides",
    category: "Library & Research",
    description: "Research guides for subjects, tools, and academic sources.",
    keywords: ["research guides", "libguides", "sources", "citation", "referencing", "apa", "research help", "subject guide"],
  },
  {
    id: "librarian-consultation",
    label: "Librarian Consultation",
    href: "https://suss.libcal.com/appointments/suss/online-consultations",
    category: "Library & Research",
    description: "Book an online consultation with a SUSS librarian.",
    keywords: ["librarian", "consultation", "appointment", "research help", "library help", "book librarian", "research consultation"],
  },
  {
    id: "library-opening-hours",
    label: "Library Opening Hours",
    href: "https://library.suss.edu.sg/opening-hours",
    category: "Library & Research",
    description: "SUSS Library opening hours.",
    keywords: ["library hours", "opening hours", "operating hours", "library timing", "closing time", "open today"],
  },
  {
    id: "financial-aid-ftug",
    label: "Financial Aid for Full-time UG",
    href: "https://www.suss.edu.sg/admissions/financial-matters/financial-aid/full-time-undergraduate",
    category: "Financial Aid",
    description: "Financial aid, bursary, and loan information for full-time undergraduate students.",
    keywords: ["financial aid", "full-time", "undergraduate", "bursary", "loan", "fees", "tuition", "subsidy", "grant", "funding", "money"],
    audience: ["Full-time UG"],
  },
  {
    id: "financial-aid-ptug",
    label: "Financial Aid for Part-time UG",
    href: "https://www.suss.edu.sg/admissions/financial-matters/financial-aid/part-time-undergraduate",
    category: "Financial Aid",
    description: "Financial aid, bursary, and loan information for part-time undergraduate students.",
    keywords: ["financial aid", "part-time", "undergraduate", "bursary", "loan", "fees", "tuition", "subsidy", "grant", "funding", "money"],
    audience: ["Part-time UG"],
  },
  {
    id: "external-scholarships-awards",
    label: "Scholarships and Awards",
    href: "https://www.suss.edu.sg/full-time-undergraduate/admissions/suss-scholarships-awards",
    category: "Financial Aid",
    description: "Scholarships and awards information for undergraduate students.",
    keywords: ["scholarship", "scholarships", "award", "awards", "financial aid", "external scholarships", "sponsorship", "funding", "tuition"],
  },
  {
    id: "discussion-room-booking",
    label: "Discussion Room Booking",
    href: "https://suss.libcal.com/spaces",
    category: "Daily Tools",
    description: "Book SUSS Library discussion rooms and study spaces.",
    keywords: ["discussion room", "room booking", "study room", "libcal", "spaces", "library room", "meeting room", "book room", "reserve room"],
    showOnHome: true,
  },
  {
    id: "campus-map-facilities",
    label: "Campus Map and Facilities",
    href: "https://www.suss.edu.sg/about-suss/resources/campus-location-and-facilities",
    category: "Campus & Facilities",
    description: "Campus location, directions, map, and facilities.",
    keywords: ["campus map", "location", "facilities", "directions", "address", "transport", "parking", "bus", "mrt", "map"],
  },
  {
    id: "psea-withdrawal-form",
    label: "PSEA Withdrawal Form",
    href: "https://form.gov.sg/686beddd68398fdc1e3058b0",
    category: "Policies & Forms",
    description: "PSEA withdrawal form on FormSG.",
    keywords: ["psea", "withdrawal", "form", "formsg", "fees", "post-secondary education account", "payment", "tuition"],
  },
  {
    id: "tma-auto-marks-deduction",
    label: "TMA Late Submission Deductions",
    href: "https://www.suss.edu.sg/docs/default-source/student-life/student-resources/tutor-marked-assignment-(tma)-auto-marks-deduction-scheme.pdf?sfvrsn=bd6c3fc7_1",
    category: "Policies & Forms",
    description: "Marks deduction rules for late tutor-marked assignments.",
    keywords: ["tma", "marks deduction", "late submission", "assignment", "auto marks deduction", "pdf", "deadline", "penalty", "late penalty", "submission"],
  },
  {
    id: "automatic-withdrawal-course",
    label: "Automatic Course Withdrawal",
    href: "https://www.suss.edu.sg/docs/default-source/student-life/student-resources/automatic-withdrawal-from-course.pdf?sfvrsn=436a5cd4_1",
    category: "Policies & Forms",
    description: "Policy covering automatic withdrawal from courses.",
    keywords: ["automatic withdrawal", "course withdrawal", "policy", "pdf", "withdraw", "drop course", "aw", "attendance", "inactive"],
  },
  {
    id: "academic-progression-ptug",
    label: "Academic Progression Policy for Part-time UG",
    href: "https://www.suss.edu.sg/docs/default-source/student-life/student-resources/academic-progression-policy-(part-time-undergraduate-students).pdf?sfvrsn=787a0318_1",
    category: "Policies & Forms",
    description: "Academic progression policy for part-time undergraduate students.",
    keywords: ["academic progression", "part-time", "undergraduate", "policy", "pdf", "minimum gpa", "cgpa", "academic standing", "graduation", "progression"],
    audience: ["Part-time UG"],
  },
  {
    id: "academic-progression-ftug",
    label: "Academic Progression Policy for Full-time UG",
    href: "https://www.suss.edu.sg/docs/default-source/student-life/student-resources/academic-progression-policy-(full-time-undergraduate-students).pdf?sfvrsn=787a0318_1",
    category: "Policies & Forms",
    description: "Academic progression policy for full-time undergraduate students.",
    keywords: ["academic progression", "full-time", "undergraduate", "policy", "pdf", "minimum gpa", "cgpa", "academic standing", "graduation", "progression"],
    audience: ["Full-time UG"],
  },
  {
    id: "academic-progression-law",
    label: "Academic Progression Policy for Law",
    href: "https://www.suss.edu.sg/docs/default-source/student-life/student-resources/academic-progression-policy-(law-students).pdf?sfvrsn=bdf65ba7_1",
    category: "Policies & Forms",
    description: "Academic progression policy for law students.",
    keywords: ["academic progression", "law", "policy", "pdf", "minimum gpa", "cgpa", "academic standing", "graduation", "progression"],
    audience: ["Law"],
  },
  {
    id: "c-three-booking",
    label: "C-three Counselling Booking",
    href: "https://c-three.suss.edu.sg",
    category: "Wellbeing & Support",
    description: "C-three counselling and life coaching booking portal.",
    keywords: ["c-three", "cthree", "c3", "counselling", "counseling", "life coaching", "booking", "wellbeing", "mental health", "support", "stress"],
  },
  {
    id: "writing-coaches",
    label: "Writing Coaches",
    href: "https://www.suss.edu.sg/academics/schools-college/english-language-support-programmes/writing-coaches",
    category: "Wellbeing & Support",
    description: "Writing coaching and English language support.",
    keywords: ["writing coach", "writing coaches", "english support", "academic writing", "essay", "report writing", "grammar", "language support"],
  },
  {
    id: "mindline",
    label: "Mindline.sg",
    href: "https://www.mindline.sg/landing",
    category: "Wellbeing & Support",
    description: "Mindline.sg mental wellness and support resource.",
    keywords: ["mindline", "mental health", "wellness", "wellbeing", "support", "stress", "anxiety", "self care", "counselling", "counseling"],
  },
  {
    id: "academic-calendars-all",
    label: "SUSS Academic Calendars",
    href: "https://www.suss.edu.sg/life-at-suss/onboarding/matriculation/academic-calendar",
    category: "Academic Planning",
    description: "Academic calendars for full-time, part-time, law, and graduate programmes.",
    keywords: ["academic calendar", "calendar", "term dates", "semester dates", "full-time", "part-time", "law", "graduate", "school term", "vacation", "study week", "exam week", "public holiday"],
  },
  {
    id: "student-services-support",
    label: "Student Services / Student Support",
    href: "mailto:students@suss.edu.sg",
    category: "Contacts",
    description: "Email student services and student support.",
    keywords: ["student services", "student support", "students", "email", "help", "enquiry", "enquiries", "admin support", "contact"],
  },
  {
    id: "career-development-contact",
    label: "Career Development",
    href: "mailto:careerdev@suss.edu.sg",
    category: "Contacts",
    description: "Email Career Development.",
    keywords: ["career development", "careerdev", "email", "career", "jobs", "internship", "resume", "cv", "contact"],
  },
  {
    id: "financial-aid-contact",
    label: "Financial Aid",
    href: "mailto:financialaid@suss.edu.sg",
    category: "Contacts",
    description: "Email Financial Aid.",
    keywords: ["financial aid", "financialaid", "email", "bursary", "loan", "fees", "tuition", "contact"],
  },
  {
    id: "canvas-lms-support",
    label: "Canvas LMS Support",
    href: "mailto:lms_support@suss.edu.sg",
    category: "Contacts",
    description: "Email Canvas LMS support.",
    keywords: ["canvas", "lms support", "lms_support", "email", "technical support", "login", "course site", "assignment issue"],
  },
  {
    id: "mymail-support",
    label: "MyMail Support",
    href: "mailto:mymail_support@suss.edu.sg",
    category: "Contacts",
    description: "Email MyMail support.",
    keywords: ["mymail", "mail support", "mymail_support", "email", "outlook", "office 365", "microsoft 365", "login", "password"],
  },
  {
    id: "it-helpdesk",
    label: "IT Helpdesk",
    href: "mailto:ithelpdesk@suss.edu.sg",
    category: "Contacts",
    description: "Email the IT Helpdesk.",
    keywords: ["it helpdesk", "it support", "technology", "email", "password", "login", "account", "wifi", "technical support"],
  },
] as const satisfies readonly StudentResource[];

export const studentResourceCategories = [
  "Daily Tools",
  "Canvas & IT",
  "Academic Planning",
  "Exams",
  "Library & Research",
  "Careers",
  "Financial Aid",
  "Campus & Facilities",
  "Policies & Forms",
  "Wellbeing & Support",
  "Contacts",
] as const satisfies readonly StudentResourceCategory[];

export const homeQuickResources = studentResources.filter((resource) => "showOnHome" in resource && resource.showOnHome);
